---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-scope-manager
  name: bluejay-scope-manager
  namespace: governify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-scope-manager
  template:
    metadata:
      labels:
        app: bluejay-scope-manager
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: NODE_ENV
            - name: PORT
              value: '80'
            - name: KEY_ASSETS_MANAGER_PRIVATE
              valueFrom: 
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: KEY_ASSETS_MANAGER_PRIVATE
            - name: KEY_SCOPE_MANAGER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: KEY_SCOPE_MANAGER
            - name: KEY_HEROKU
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: KEY_HEROKU
            - name: KEY_GITHUB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: KEY_GITHUB
            - name: GOV_INFRASTRUCTURE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: GOV_INFRASTRUCTURE
          image: governify/scope-manager:develop
          imagePullPolicy: Always
          name: bluejay-scope-manager
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 400Mi
      securityContext: {}
