apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: governify
type: Opaque
stringData:
    # INFRASTRUCTURE
    GOV_INFRASTRUCTURE: {{ .Values.gov_infrastructure }}
    NODE_ENV: {{ .Values.node_env }}
    KEY_ASSETS_MANAGER_PRIVATE: {{ .Values.key_assets_manager_private }}
    KEY_SCOPE_MANAGER: {{ .Values.key_scope_manager }}
    KEY_HEROKU: {{ .Values.key_heroku }}
    KEY_GITHUB: {{ .Values.key_github }}
    
