apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-scope-manager
  name: bluejay-scope-manager
  namespace: governify
spec:
  {{- if eq .Values.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: http
      {{- if eq .Values.node_env "development" }}
      nodePort: 5700
      {{- end }}
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bluejay-scope-manager
