---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-registry
  name: bluejay-registry
  namespace: governify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-registry
  template:
    metadata:
      labels:
        app: bluejay-registry
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: NODE_ENV
            - name: PORT
              value: '80'
            - name: GOV_INFRASTRUCTURE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: GOV_INFRASTRUCTURE

          image: governify/registry:develop
          imagePullPolicy: Always
          name: bluejay-registry
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 500Mi
      securityContext: {}
