{{- if eq .Values.node_env "production" }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpproxy-bluejay-registry
  namespace: governify
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers "Access-Control-Allow-Origin: $http_origin";
spec:
  virtualhost:
    fqdn: registry{{ .Values.services_prefix }}{{ .Values.dns_suffix }}
    {{- if .Values.certs }}
    tls:
      secretName: {{ .Release.Name }}-cert
    {{- end }}
  routes:
  - services:
    - name: bluejay-registry
      port: 80
    loadBalancerPolicy:
      strategy: Cookie
{{- end}}