apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: governify
type: Opaque
stringData:
    # INFRASTRUCTURE
    GOV_INFRASTRUCTURE: {{ .Values.gov_infrastructure }}
    NODE_ENV: {{ .Values.node_env }}