apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-registry
    idle: 'true'
  name: bluejay-registry
  namespace: governify
spec:
  {{- if eq .Values.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: http
      {{- if eq .Values.node_env "development" }}
      nodePort: 5400
      {{- end }}
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bluejay-registry
