---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bluejay-mongo-registry
  namespace: governify
  labels:
    app: bluejay-mongo-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
