apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-mongo-registry
  name: bluejay-mongo-registry
  namespace: governify
spec:
  {{- if eq .Values.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: '27017'
      port: 27017
      {{- if eq .Values.node_env "development" }}
      nodePort: 5001
      {{- end }}
      protocol: TCP
      targetPort: 27017
  selector:
    app: bluejay-mongo-registry
