---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bluejay-redis-ec
  namespace: governify
  labels:
    app: bluejay-redis-ec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
