apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-redis-ec
  name: bluejay-redis-ec
  namespace: governify
spec:
  {{- if eq .Values.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: '6379'
      port: 6379
      {{- if eq .Values.node_env "development" }}
      nodePort: 5003
      {{- end }}
      protocol: TCP
      targetPort: 6379
  selector:
    app: bluejay-redis-ec
