---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-assets-manager
  name: bluejay-assets-manager
  namespace: governify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-assets-manager
  template:
    metadata:
      labels:
        app: bluejay-assets-manager
    spec:
      containers:
        - env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "80"
          - name: LOGIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: LOGIN_USER 
          - name: LOGIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: LOGIN_PASSWORD 
          - name: DNS_SUFFIX
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: DNS_SUFFIX 
          - name: SERVICES_PREFIX
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: SERVICES_PREFIX
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: KEY_ASSETS_MANAGER_PRIVATE
          - name: ASSETS_REPOSITORY
            value: 'https://github.com/governify/assets-bluejay'
          - name: ASSETS_REPOSITORY_BRANCH
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: ASSETS_REPOSITORY_BRANCH
          {{- if eq .Values.node_env "development" }}
          - name: GOV_INFRASTRUCTURE
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-env
                key: ASSETS_GOV_INFRASTRUCTURE
          {{- end }}
          image: governify/assets-manager:develop
          imagePullPolicy: Always
          name: bluejay-assets-manager
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 900Mi

