{{- if eq .Values.node_env "production" }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpproxy-assetsmanager
  namespace: governify
spec:
  virtualhost:
    fqdn: assets{{ .Values.services_prefix }}{{ .Values.dns_suffix }}
    {{- if .Values.certs }}
    tls:
      secretName: {{ .Release.Name }}-cert
    {{- end }}
  routes:
  - services:
    - name: bluejay-assets-manager
      port: 80
    loadBalancerPolicy:
      strategy: Cookie
  - conditions:
    - prefix: /
    enableWebsockets: true
    services:
    - name: bluejay-assets-manager
      port: 80
{{- end }}
