apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: governify
type: Opaque
stringData:
    SERVICES_PREFIX: {{ .Values.services_prefix }}
    DNS_SUFFIX: {{ .Values.dns_suffix }}

    # CREDENTIALS (For different services)
    LOGIN_USER: {{ .Values.user_assets }}
    LOGIN_PASSWORD: {{ .Values.pass_assets }}
    KEY_ASSETS_MANAGER_PRIVATE: {{ .Values.key_assets_manager_private }}
    
    # INFRASTRUCTURE
    NODE_ENV: {{ .Values.node_env }}
    ASSETS_REPOSITORY_BRANCH: {{ .Values.assets_repository_branch }}
    {{- if eq .Values.node_env "development" }}
    ASSETS_GOV_INFRASTRUCTURE: /home/project/public/infrastructure-local.yaml
    {{- end }}
