curl "https://dinahosting.com/special/api.php?AUTH_USER=$1&AUTH_PWD=$2&responseType=Json&domain=$3&hostname=ui.$4&ip=$5&command=Domain_Zone_AddTypeA"
curl "https://dinahosting.com/special/api.php?AUTH_USER=$1&AUTH_PWD=$2&responseType=Json&domain=$3&hostname=dashboard.$4&ip=$5&command=Domain_Zone_AddTypeA"
curl "https://dinahosting.com/special/api.php?AUTH_USER=$1&AUTH_PWD=$2&responseType=Json&domain=$3&hostname=sm.$4&ip=$5&command=Domain_Zone_AddTypeA"
curl "https://dinahosting.com/special/api.php?AUTH_USER=$1&AUTH_PWD=$2&responseType=Json&domain=$3&hostname=reporter.$4&ip=$5&command=Domain_Zone_AddTypeA"
curl "https://dinahosting.com/special/api.php?AUTH_USER=$1&AUTH_PWD=$2&responseType=Json&domain=$3&hostname=registry.$4&ip=$5&command=Domain_Zone_AddTypeA"