apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: governify
type: Opaque
stringData:

    # CREDENTIALS (For different services)
    KEY_SCOPE_MANAGER: {{ .Values.key_scope_manager }}
    KEY_GITHUB: {{ .Values.key_github }}
    KEY_PIVOTAL: {{ .Values.key_pivotal }}
    KEY_TRAVIS_PUBLIC: {{ .Values.key_travis_public }}
    KEY_TRAVIS_PRIVATE: {{ .Values.key_travis_private }}
    KEY_HEROKU: {{ .Values.key_heroku }}
    KEY_CODECLIMATE: {{ .Values.key_codeclimate }}

    # INFRASTRUCTURE
    NODE_ENV: {{ .Values.node_env }}
    GOV_INFRASTRUCTURE: {{ .Values.gov_infrastructure }}
