---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-render
  name: bluejay-render
  namespace: governify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-render
  template:
    metadata:
      labels:
        app: bluejay-render
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: NODE_ENV
            - name: PORT
              value: '80'
            - name: LOGIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: LOGIN_USER
            - name: LOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: LOGIN_PASSWORD
            - name: DEFAULT_VIEW
              value: 'http://bluejay-assets-manager/api/v1/public/renders/index/view.html'
            - name: DEFAULT_CONTROLLER
              value: 'http://bluejay-assets-manager/api/v1/public/renders/index/controller.js'
            - name: DEFAULT_MODEL
              value: 'http://bluejay-assets-manager/api/v1/public/renders/index/model.json'
            - name: LAYOUT
              value: bootstrap5.html
            - name: GOV_INFRASTRUCTURE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: GOV_INFRASTRUCTURE
                  
          image: governify/render:develop
          imagePullPolicy: Always
          name: bluejay-render
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 500Mi
      securityContext: {}
