apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: governify
type: Opaque
stringData:
    # CREDENTIALS (For different services)
    LOGIN_USER: {{ .Values.user_render }}
    LOGIN_PASSWORD: {{ .Values.pass_render }}

    # INFRASTRUCTURE
    GOV_INFRASTRUCTURE: {{ .Values.gov_infrastructure }}
    NODE_ENV: {{ .Values.node_env }}
