apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-render
  name: bluejay-render
  namespace: governify
spec:
  {{- if eq .Values.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: bluejay-render
      port: 80
      protocol: TCP
      targetPort: 80
      {{- if eq .Values.node_env "development" }}
      nodePort: 5100
      {{- end }}
  selector:
    app: bluejay-render
