---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-director
  name: bluejay-director
  namespace: governify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-director
  template:
    metadata:
      labels:
        app: bluejay-director
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: NODE_ENV
            - name: PORT
              value: '80'
            - name: GOV_INFRASTRUCTURE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-env
                  key: GOV_INFRASTRUCTURE
          image: governify/director:develop
          imagePullPolicy: Always
          name: bluejay-director
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 400Mi
      securityContext: {}
