---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bluejay-influx-reporter
  namespace: governify
  labels:
    app: bluejay-influx-reporter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
